FROM hashicorp/packer:1.10 AS packer-plugins
RUN packer plugins install github.com/bdwyertech/chef \
    && packer plugins install github.com/hashicorp/amazon \
    && packer plugins install github.com/bdwyertech/amazon \
    && packer plugins install github.com/hashicorp/ansible

FROM python:3.11-alpine3.21
COPY --from=packer-plugins /root/.config/packer/plugins /root/.config/packer/plugins

ARG BUILD_DATE
ARG VCS_REF

LABEL org.opencontainers.image.title="image-build-utils" \
    org.opencontainers.image.authors="Brian Dwyer <bdwyertech@github.com>" \
    org.opencontainers.image.source="https://github.com/bdwyertech/docker-image-build-utils.git" \
    org.opencontainers.image.revision=$VCS_REF \
    org.opencontainers.image.created=$BUILD_DATE \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/bdwyertech/docker-image-build-utils.git"

# Update PIP & Install PIPEnv
RUN python -m pip install --upgrade pip \
    && python -m pip install --upgrade pipenv \
    && rm -rf ~/.cache/pip

ARG DOCKER_TAG="py311"
RUN if [ -z "${DOCKER_TAG##*ansible*}" ] ; then \
    apk add --no-cache openssh-client \
    && python -m pip install ansible jmespath \
    && rm -rf ~/.cache/pip \
    ; fi

# Update & Install Ruby
RUN apk update && apk upgrade \
    && apk add --no-cache bash ca-certificates curl git ruby ruby-etc ruby-json wget \
    && echo 'gem: --no-document' > /etc/gemrc

# Install Berkshelf
RUN apk add --no-cache --virtual .build-deps ruby-dev build-base linux-headers \
    && gem install berkshelf \
    && apk del .build-deps \
    && rm -rf ~/.gem

# Trivy
ARG TARGETPLATFORM=linux/amd64
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN \
    DOCKER_ARCH=$(case ${TARGETPLATFORM} in \
    "linux/amd64")   echo -e "Linux-64bit" ;; \
    "linux/arm64")   echo -e "Linux-ARM64" ;; \
    *)               echo "" ;; esac) \
    && (curl -H "Authorization: Bearer $GITHUB_TOKEN" -sfkL "$(curl -H 'Authorization: Bearer '"$GITHUB_TOKEN" -Ls https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -o -E 'https://.+?_'"${DOCKER_ARCH}"'.tar.gz' -m 1)" | tar zxf - --directory /usr/local/bin)

# Hide Ruby Warnings
ENV RUBYOPT='-W0'
