FROM hashicorp/packer:1.10 AS packer-plugins
RUN packer plugins install github.com/bdwyertech/chef \
    && packer plugins install github.com/hashicorp/amazon \
    && packer plugins install github.com/bdwyertech/amazon \
    && packer plugins install github.com/hashicorp/ansible

FROM python:3.12-alpine3.22
COPY --from=packer-plugins /root/.config/packer/plugins /root/.config/packer/plugins

ARG BUILD_DATE
ARG VCS_REF

LABEL org.opencontainers.image.title="image-build-utils" \
    org.opencontainers.image.authors="Brian Dwyer <bdwyertech@github.com>" \
    org.opencontainers.image.source="https://github.com/bdwyertech/docker-image-build-utils.git" \
    org.opencontainers.image.revision=$VCS_REF \
    org.opencontainers.image.created=$BUILD_DATE \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/bdwyertech/docker-image-build-utils.git"

# Update PIP & Install PIPEnv
RUN python -m pip install --upgrade pip \
    && python -m pip install --upgrade pipenv \
    && rm -rf ~/.cache/pip

ARG DOCKER_TAG="py312"
RUN if [ -z "${DOCKER_TAG##*ansible*}" ] ; then \
    apk add --no-cache openssh-client \
    && python -m pip install ansible jmespath \
    && rm -rf ~/.cache/pip \
    ; fi

# Update & Install Ruby
RUN apk update && apk upgrade \
    && apk add --no-cache bash ca-certificates curl git ruby ruby-etc ruby-json wget \
    && echo 'gem: --no-document' > /etc/gemrc

# Install Berkshelf
RUN apk add --no-cache --virtual .build-deps ruby-dev build-base linux-headers libffi-dev \
    && gem install berkshelf \
    && apk del .build-deps \
    && rm -rf ~/.gem

# Trivy
ARG TARGETPLATFORM=linux/amd64
RUN DOCKER_ARCH=$(case ${TARGETPLATFORM} in \
    "linux/amd64")   echo -e "Linux-64bit" ;; \
    "linux/arm64")   echo -e "Linux-ARM64" ;; \
    *)               echo "" ;; esac) \
    && (curl -sfkL "$(curl -Ls https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -o -E "https://.+?_${DOCKER_ARCH}.tar.gz" -m 1)" | tar zxf - --directory /usr/local/bin)

# Hide Ruby Warnings
ENV RUBYOPT='-W0'

# (curl -sfL "$(curl -Ls https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -o -E "https://.+?_Linux-64bit.tar.gz" -m 1)" | tar zxf - --directory /usr/local/bin)

# curl -vkfL "https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz" | tar zxf - --directory /usr/local/bin


# packer plugins install github.com/bdwyertech/chef

# .config/packer/plugins
